package cn.dehui.task.keywordtool.browser.controller.util;

public enum Status {
    UNSTARRED, KEYWORD_SEARCHING, URL_SEARCHING, WAIT_FOR_CM, WAIT_FOR_KEYWORD_PLAN_1ST_PAGE, WAIT_FOR_KEYWORD_PLAN_2ND_PAGE, EMTER_TARGET_TOOL, SEARCHING_RESULT, WAIT_FOR_FC, WAIT_FOR_MP
}